
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 22;
  public static final int MENOR = 17;
  public static final int SENAO = 13;
  public static final int ENTAO = 12;
  public static final int IDENT = 2;
  public static final int IGUAL = 18;
  public static final int COMP = 9;
  public static final int PARENTESE2 = 26;
  public static final int ELGIO = 6;
  public static final int PARENTESE1 = 25;
  public static final int INTEIRO = 7;
  public static final int PT = 5;
  public static final int NUM = 3;
  public static final int MAIS = 21;
  public static final int SEPARADOR = 20;
  public static final int MULT = 23;
  public static final int EOF = 0;
  public static final int FUNC = 4;
  public static final int DIFERENTE = 19;
  public static final int DIV = 24;
  public static final int error = 1;
  public static final int MAIOR = 16;
  public static final int SE = 11;
  public static final int ZERO = 8;
  public static final int ENQUANTO = 10;
  public static final int FIM = 15;
  public static final int INICIO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "NUM",
  "FUNC",
  "PT",
  "ELGIO",
  "INTEIRO",
  "ZERO",
  "COMP",
  "ENQUANTO",
  "SE",
  "ENTAO",
  "SENAO",
  "INICIO",
  "FIM",
  "MAIOR",
  "MENOR",
  "IGUAL",
  "DIFERENTE",
  "SEPARADOR",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "PARENTESE1",
  "PARENTESE2"
  };
}

